TrashDIR = /home/xiaoxian/.local/share/Trash/files/


clean_data:
	- mv *.poly *.ele *.node *.edge *.png *.gnuplot $(TrashDIR)
clean_obj:
	- mv *.o $(TrashDIR)
clean_complete:
	make clean_data
	make clean_obj
